### ISSUE TITLE
No clear how to install/use instructions

### ISSUE THREAD

**Issue by smcpoland** [Bonitasoft-Community/page_longboard#1]
Hi there,

issue is No clear how to install/use instructions

I've tried this in 7.3.2
1. Login -> Change to Administrator
2. Resources -> Add No longboard
3. Application -> Create Application -> longboard
4. Pages -> Add and make home page longboard
5. click on URL...

All I get is a Server error 500.  Log as follows:

`2016-10-14 11:40:44.343 +1300 WARNING: org.bonitasoft.livingapps.LivingApplicationPageServlet Error while trying to render the application page custompage_longboard
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
C:\Bonita\7xx\73x\732\00 Scratch\workspace\tomcat\temp\bonita_portal_10336@Gube1000\tenants\1\pages\custompage_longboard\Index.groovy: 42: unable to resolve class com.bonitasoft.engine.api.TenantAPIAccessor
 @ line 42, column 1.
   import com.bonitasoft.engine.api.TenantAPIAccessor;
   ^

C:\Bonita\7xx\73x\732\00 Scratch\workspace\tomcat\temp\bonita_portal_10336@Gube1000\tenants\1\pages\custompage_longboard\Index.groovy: 47: unable to resolve class com.bonitasoft.engine.api.PlatformMonitoringAPI
 @ line 47, column 1.
   import com.bonitasoft.engine.api.PlatformMonitoringAPI;
   ^

2 errors

```
at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:946)
at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:593)
at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:542)
at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:254)
at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:195)
at org.bonitasoft.console.common.server.page.CustomPageService.registerPage(CustomPageService.java:128)
at org.bonitasoft.console.common.server.page.PageRenderer.displayGroovyPage(PageRenderer.java:118)
at org.bonitasoft.console.common.server.page.PageRenderer.displayCustomPage(PageRenderer.java:77)
at org.bonitasoft.console.common.server.page.PageRenderer.displayCustomPage(PageRenderer.java:60)
at org.bonitasoft.livingapps.LivingApplicationPageServlet.doGet(LivingApplicationPageServlet.java:125)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
at org.bonitasoft.livingapps.LivingApplicationPageServlet.service(LivingApplicationPageServlet.java:83)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.isAuthorized(AuthenticationFilter.java:147)
at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.doAuthenticationFiltering(AuthenticationFilter.java:130)
at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:117)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
at org.bonitasoft.console.security.SessionFixationValve.invoke(SessionFixationValve.java:77)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Unknown Source)
```

2016-10-14 11:40:44.344 +1300 SEVERE: org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/bonita].[livingApplicationPageServlet] Servlet.service() for servlet [livingApplicationPageServlet] in context with path [/bonita] threw exception [startup failed:
C:\Bonita\7xx\73x\732\00 Scratch\workspace\tomcat\temp\bonita_portal_10336@Gube1000\tenants\1\pages\custompage_longboard\Index.groovy: 42: unable to resolve class com.bonitasoft.engine.api.TenantAPIAccessor
 @ line 42, column 1.
   import com.bonitasoft.engine.api.TenantAPIAccessor;
   ^

C:\Bonita\7xx\73x\732\00 Scratch\workspace\tomcat\temp\bonita_portal_10336@Gube1000\tenants\1\pages\custompage_longboard\Index.groovy: 47: unable to resolve class com.bonitasoft.engine.api.PlatformMonitoringAPI
 @ line 47, column 1.
   import com.bonitasoft.engine.api.PlatformMonitoringAPI;
   ^

2 errors
] with root cause
javax.servlet.ServletException: startup failed:
C:\Bonita\7xx\73x\732\00 Scratch\workspace\tomcat\temp\bonita_portal_10336@Gube1000\tenants\1\pages\custompage_longboard\Index.groovy: 42: unable to resolve class com.bonitasoft.engine.api.TenantAPIAccessor
 @ line 42, column 1.
   import com.bonitasoft.engine.api.TenantAPIAccessor;
   ^

C:\Bonita\7xx\73x\732\00 Scratch\workspace\tomcat\temp\bonita_portal_10336@Gube1000\tenants\1\pages\custompage_longboard\Index.groovy: 47: unable to resolve class com.bonitasoft.engine.api.PlatformMonitoringAPI
 @ line 47, column 1.
   import com.bonitasoft.engine.api.PlatformMonitoringAPI;
   ^

2 errors

```
at org.bonitasoft.livingapps.LivingApplicationPageServlet.handleException(LivingApplicationPageServlet.java:209)
at org.bonitasoft.livingapps.LivingApplicationPageServlet.doGet(LivingApplicationPageServlet.java:132)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
at org.bonitasoft.livingapps.LivingApplicationPageServlet.service(LivingApplicationPageServlet.java:83)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.isAuthorized(AuthenticationFilter.java:147)
at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.doAuthenticationFiltering(AuthenticationFilter.java:130)
at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:117)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
at org.bonitasoft.console.security.SessionFixationValve.invoke(SessionFixationValve.java:77)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Unknown Source)`
```

**Comment by pierre-yves-monnet** [comment]
Should be fixed in the current version
